
#ifndef RTCONFIG_PREINC_H__
#define RTCONFIG_PREINC_H__

/* Automatically generated file; DO NOT EDIT. */
/* RT-Thread pre-include file */

#define BLHS_SUPPORT
#define BUILD_KIT_PROCE84_EVK_M55
#define COMPONENT_55500
#define COMPONENT_55500A1
#define COMPONENT_APP_KIT_PSE84_EVAL_EPC2
#define COMPONENT_CM55
#define COMPONENT_CM55_0
#define COMPONENT_Debug
#define COMPONENT_GCC_ARM
#define COMPONENT_GFXSS
#define COMPONENT_HARDFP
#define COMPONENT_HCI_UART
#define COMPONENT_MTB_DEVICE_SUPPORT
#define COMPONENT_MTB_HAL
#define COMPONENT_MW_ASYNC_TRANSFER
#define COMPONENT_MW_CMSIS
#define COMPONENT_MW_CORE_LIB
#define COMPONENT_MW_CORE_MAKE
#define COMPONENT_MW_RETARGET_IO
#define COMPONENT_NON_SECURE_DEVICE
#define COMPONENT_PSE84
#define COMPONENT_RTOS_AWARE
#define COMPONENT_SM
#define CORE_NAME_CM55_0 1
#define CYBSP_MCUBOOT_HEADER_SIZE 0x400
#define CY_APPNAME_proj_cm55
#define CY_PDL_FLASH_BOOT
#define CY_RETARGET_IO_CONVERT_LF_TO_CRLF
#define CY_RTOS_AWARE
#define CY_SUPPORTS_DEVICE_VALIDATION
#define CY_TARGET_BOARD APP_KIT_PSE84_EVAL_EPC2
#define DEBUG
#define DISABLE_FLOAT_API
#define FIXED_POINT 1
#define FLASH_BOOT
#define HAVE_ALLOCA_H
#define HAVE_LRINTF
#define LFS_CONFIG lfs_config.h
#define OPUS_ARM_INLINE_ASM
#define OPUS_ARM_INLINE_EDSP
#define OPUS_ARM_INLINE_MEDIA
#define OPUS_BUILD
#define PSE846GPS2DBZC4A
#define RT_USING_LIBC
#define RT_USING_NEWLIBC
#define TARGET_APP_KIT_PSE84_EVAL_EPC2
#define TRXV5
#define USE_ALLOCA
#define _BAREMETAL 0
#define _POSIX_C_SOURCE 1
#define _REENT_SMALL
#define __RTTHREAD__

#endif /*RTCONFIG_PREINC_H__*/
