from building import *
import os

cwd = GetCurrentDir()
LIBS = []
LIBPATH = []
# Add all subdirectories to include path
path = []
path += [cwd]
path += [cwd + '/litegfx/adapt', cwd + '/litegfx/plat', cwd + '/litegfx/vglite/include', cwd + '/sample', cwd + '/sample/lz4', cwd + '/sample/resource/AnimatedEmoji']

src = Glob('*.c') + Glob('*.cpp')
src += Glob('litegfx/adapt/*.c') + Glob('litegfx/plat/*.c')
src += Glob('sample/*.c') + Glob('sample/lz4/*.c') + Glob('sample/resource/AnimatedEmoji/*.c')
LIBS+= ['lx_vglite']
LIBPATH += [cwd + '/litegfx/vglite']

group = DefineGroup('xiaozhi_ui', src, depend=[''], LIBS = LIBS, LIBPATH=LIBPATH, CPPPATH=path)
list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')