import rtconfig
from building import *
import os

cwd  = GetCurrentDir()
path = [cwd]
src  = Glob('*.c')

if GetDepend('RT_USING_CHERRYUSB'):
    path += [cwd + '/../libraries/components/CherryUSB-1.6.0/core']
    path += [cwd + '/../libraries/components/CherryUSB-1.6.0/class/video']
    path += [cwd + '/../libraries/Common/board/ports/usb']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
