from building import *
import os

cwd = GetCurrentDir()
xiaozhi_dir = os.path.dirname(cwd)

# Edge Impulse SDK paths
edge_impulse_dir = xiaozhi_dir + '/../../../edge-impulse'
EI_SDK_PATH = edge_impulse_dir + '/edge-impulse-sdk'

# Include paths - combine xiaozhi and edge-impulse
path = []
# xiaozhi paths
path += [xiaozhi_dir, xiaozhi_dir + '/ui']
# edge-impulse paths
path += [edge_impulse_dir, edge_impulse_dir + '/model-parameters']
path += [EI_SDK_PATH + '/classifier', EI_SDK_PATH + '/dsp', EI_SDK_PATH + '/porting']
path += [EI_SDK_PATH + '/CMSIS/Core/Include', EI_SDK_PATH + '/CMSIS/DSP/Include']

# Source files
src = Glob('*.c') + Glob('*.cpp')

# Edge Impulse compiler flags
LOCAL_CFLAGS = ' -D__RTTHREAD__ -DEI_PORTING_RTTHREAD=1'
LOCAL_CFLAGS += ' -DTF_LITE_STATIC_MEMORY -DTF_LITE_DISABLE_X86_NEON'
LOCAL_CFLAGS += ' -DEI_CLASSIFIER_TFLITE_ENABLE_CMSIS_NN=1 -DEIDSP_USE_CMSIS_DSP=1'
LOCAL_CFLAGS += ' -DEIDSP_LOAD_CMSIS_DSP_SOURCES=1 -DEIDSP_QUANTIZE_FILTERBANK=0'
LOCAL_CFLAGS += ' -DARM_MATH_CM55 -DARM_MATH_DSP -DARM_MATH_LOOPUNROLL -DARM_MATH_AUTOVECTORIZE'

LOCAL_CXXFLAGS = LOCAL_CFLAGS + ' -std=c++11 -fno-rtti -fno-exceptions -fno-threadsafe-statics'
LOCAL_CXXFLAGS += ' -Wno-sign-compare -Wno-strict-aliasing'

group = DefineGroup('xiaozhi_wake_word', src, depend=[''],
                    CPPPATH=path,
                    LOCAL_CFLAGS=LOCAL_CFLAGS,
                    LOCAL_CXXFLAGS=LOCAL_CXXFLAGS)

Return('group')