import os
from building import *

cwd  = GetCurrentDir()
path = []
path += [cwd]
# Add source code
src = Glob('*.c')

group = DefineGroup('xiaozhi_ui', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
