from building import *
import os

cwd     = GetCurrentDir()

# Add all subdirectories to include path
path = []
path += [cwd]
path += [cwd + '/..']
path += [cwd + '/ui', cwd + '/webnet', cwd + '/iot', cwd + '/mcp']
# Add edge-impulse directory for wake word detection
path += [cwd + '/../../edge-impulse']

src = Glob('*.c') + Glob('*.cpp')

group = DefineGroup('xiaozhi', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
